"""Codegen a browser-free replay client from a capture. (hydra gen)

Turn discovered endpoints into a standalone Python file that replays them with
httpx — no browser needed after discovery. Captured auth (cookies / bearer /
api-key) is embedded so it works out of the box; when it expires you re-run
`hydra gen` (or `hydra login`) to refresh. This is the "point at a site → get a
runnable client" step: Hydra writes the scraper you'd otherwise hand-write.
"""
from __future__ import annotations

import re

# request headers worth carrying into the replay client (auth + identity)
_KEEP = ("cookie", "authorization", "x-api-key", "x-algolia-api-key",
         "x-requested-with", "user-agent", "referer", "origin")


def _fn_name(url: str, used: set) -> str:
    base = url.split("?")[0].rstrip("/").split("/")[-1] or "endpoint"
    base = re.sub(r"[^0-9A-Za-z]+", "_", base).strip("_").lower() or "endpoint"
    if not base[0].isalpha():
        base = "ep_" + base
    name, i = base, 2
    while name in used:
        name, i = f"{base}_{i}", i + 1
    used.add(name)
    return name


def _short(url: str) -> str:
    return url if len(url) <= 90 else url[:90] + "…"


_TEMPLATE = '''"""Browser-free client for {host}
Generated by `hydra gen {url}`.

⚠ Auth (cookies / tokens) below was captured at generation time and WILL expire —
re-run `hydra gen` to refresh. Treat this file as a credential; don't commit it.
"""
import httpx

HEADERS = {{
{headers}
}}


def _client() -> httpx.Client:
    return httpx.Client(headers=HEADERS, timeout=30, follow_redirects=True)


{funcs}

if __name__ == "__main__":
    client = _client()
{calls}
'''


def generate_client(url: str, candidates: list) -> str:
    """Emit a standalone httpx client (as source text) for the given candidates."""
    headers: dict[str, str] = {}
    for c in candidates:
        for k, v in (c.request_headers or {}).items():
            if k.lower() in _KEEP and k not in headers:
                headers[k] = v

    used: set = set()
    funcs, calls = [], []
    for c in candidates:
        name = _fn_name(c.url, used)
        if c.method == "GET":
            req = f'    r = client.get({c.url!r})'
        else:
            body = c.post_data or ""
            req = f'    r = client.request({c.method!r}, {c.url!r}, content={body!r})'
        funcs.append(
            f'def {name}(client: httpx.Client):\n'
            f'    """{c.method} {_short(c.url)}"""\n'
            f'{req}\n'
            f'    r.raise_for_status()\n'
            f'    return r.json()\n')
        calls.append(f'    print({name!r}, "→", str({name}(client))[:200])')

    host = url.split("://", 1)[-1].split("/", 1)[0]
    header_lines = ",\n".join(f'    {k!r}: {v!r}' for k, v in headers.items()) or "    # (none)"
    return _TEMPLATE.format(host=host, url=url, headers=header_lines,
                            funcs="\n\n".join(funcs), calls="\n".join(calls) or "    pass")
